version: '3.9'

networks:
  none:

services:
  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      none:
        aliases:
          - db-redis

#  celery:
#    build:
#      context: .
#      dockerfile: Dockerfile.celery
#    environment:
#      CELERY_BROKER: "redis://db-redis:6379/1"
#      CELERY_BACKEND: "redis://db-redis:6379/2"
#    container_name: celery
#    networks:
#      none:
#    volumes:
#      - ./app:/app